### ISSUE TITLE
MODULE_NOT_FOUND error in Ubuntu 20

### ISSUE THREAD

**Issue by 0xPrial** [dbogatov/broken-links-inspector#4]
I am getting below error in **Ubuntu 20**

```
~ # npm i -g broken-links-inspector

added 34 packages, and audited 35 packages in 3s

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
 ~ # bli
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /usr/lib/node_modules/broken-links-inspector/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/broken-links-inspector/dist/index.js:20:36)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/lib/node_modules/broken-links-inspector/dist/index.js' ]
}
```

**Comment by dbogatov** [comment]
It may be due to older version of node. Could you share your note and npm versions?

if it is the case, let me see if I can drop the promises package and you will be able to run it on your machine.

**Comment by 0xPrial** [comment]
Great, I just fixed this by updating `NodeJS` to latest version :D
